apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-apigateway
  namespace: kong
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kong
  source:
    chart: kong
    repoURL: https://charts.konghq.com
    targetRevision: 1.16.1
    helm:
      releaseName: apigateway
      valueFiles:
      - ../argo-templates/kong-cp-values.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true